### PR TITLE
consider using latest SDK, Enabled based on environments from config 

### PR DESCRIPTION
**Pull request by mhadaily**
Hi, 

Thank you for your Plugin. I added a refinement to the config, it's very likely that NODE_ENV is modified or we want to log error for different environments as well. for instance, what we have 5 different environments and expect Development, we'd like to log errors for others as our codebase is pretty big and testing before releasing to prod is very very likely. 

Therefore, with this PR, it's possible to add environment into config file where it's under control and it's not hard coded in plugin. 

Thanks,

### CODE REVIEW

**Comment by bradleyayers** [comment]
This looks great. I'd like to be able to specify the `whitelistUrls` config, which AFAICT isn't possible using the legacy API.

**Comment by mhadaily** [comment]
@bradleyayers yes true. I am not sure what's wrong with PR that didn't get merged yet.

**Comment by bradleyayers** [comment]
@octalmage is there anything you feel this PR is missing?

**Comment by all9lives** [comment]
Would be great to see this plugin updated to the latest version of Sentry, so we can use the current APIs.  
# 🙏🏻

**Comment by sedubois** [comment]
Maybe this codebase could be forked/moved into the Gatsby repo, to be managed by the community?

**Comment by mhadaily** [comment]
Sent a PR to https://github.com/gatsbyjs/gatsby/pull/10412, it would be nice if they approve it. @sedubois @all9lives @bradleyayers you can maybe support this PR. I hope everyone can benefit from that.

**Comment by octalmage** [comment]
I've released this to npm under v1.0.0! Thanks for the contribution!

**Pull request merged**
